### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by Adam-it** [pnp/vscode-pnp-powershell#1]
## Aim

The aim is to migrate PnP PowerShell VS Code extension to this repo and prepare the repository

## ToDo

- [x] Migrate the code base from https://github.com/Adam-it/pnp-powershell-extension
- [x] Migrate issues from https://github.com/Adam-it/pnp-powershell-extension
- [x] Refactor product readme
- [x] Prepare wiki with guidance
- [x] Prepare issue and PR templates
- [x] Recreate publish process
- [x] Add Contribution guidance
- [x] Add labels
- [x] Do a test release
- [x] Add secret
- [ ] Notify the team
- [x] Make repo public
- [x] Configure Repo
- [x] Add to PnP org site
- [x] Issues
    - [x] Refactor to reduce webviews: the command list view could be done using standard VS Code functionalities
    - [x] The webviews could be refactored not to be based on vite to reduce the amount of files and not needed configs
    - [x] ...??
